"""Increase password_hash length

Revision ID: 78284a77d425
Revises: 81b6c93dba34
Create Date: 2025-09-21 14:24:29.198561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78284a77d425'
down_revision = '81b6c93dba34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###
